### PR TITLE
some improvements !

### PR DESCRIPTION
**Pull request by Amar-Dev1**
Hi @SairaBatool123,

I came across the admission form in your project and made some contributions to improve it. I enjoy contributing to projects like yours and hope these changes add value to your work. I also hope they provide insights or inspire new ideas for you.

 **  key changes 🤓

app.js
 1. convert var keywords to let keyword to make efficient and apply ES6 Standards 👨‍💻
 2. store ( student From, editor, editStudentDetail ) in a variables to . this for best practice 🚀

style.css

 1.  I removed the position relative from the submit button , no needed for it 🤓 
 2.  I added some cool styles to inputs ✨
 3. I also removed the position relative here , no needed for it 🤓 
 4. I removed the height style from the box, because often, the Specific height or width destroy the design 

Looking forward to your feedback !

 happy coding 😄

### CODE REVIEW

**Comment by SairaBatool123** [comment]
Hello can you share your hosting link?

**Comment by SairaBatool123** [comment]
Sorry for late responding I'm stuck in my mids so that's why I'm inactive
all over social media platform I have saw your message pop-up on LinkedIn
too but not opening right now! I'll catch you after a while! Hopefully On
up coming Sunday!

**Comment by Amar-Dev1** [comment]
Sure ! 

Here is the host link :
https://amar-dev1.github.io/Addmission_Form

good luck on mids ! be Strong !

**Comment by SairaBatool123** [comment]
Thanks 😊

**Comment by SairaBatool123** [comment]
Not much changes you have make but still I'll merge it okay!! 🌼👍

**Comment by Amar-Dev1** [comment]
yes I know that 😂 . I just wanted to point out to specific things on code , so that we get benefit from it .

thanks for your cooperation !

**Comment by SairaBatool123** [comment]
Hahaha with padding if you really want so you can put some functionality
with js

**Comment by Amar-Dev1** [comment]
if you want that , i will 😂

**Comment by SairaBatool123** [comment]
Yes please 😅🌼

**Pull request closed without merging**
